version: '3.9'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  hacker-news:
    restart: on-failure
    build: ./
    ports:
      - '3001:3001'
      - '3002:3002'
      - '3003:3003'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_LEVEL=debug
  nginx:
    build: ./nginx
    ports:
      - '3000:3000'
    depends_on:
      - hacker-news